### ISSUE TITLE
when creating wagon with embedded python, it fails on missing venv env var.

### ISSUE THREAD

**Issue by gilzellner** [cloudify-cosmo/wagon#58] opened 2016-09-12 09:54 UTC
DEBUG - installing to build/bdist.linux-x86_64/wheel
DEBUG - running install
DEBUG - Traceback (most recent call last):
DEBUG - File "<string>", line 1, in <module>
DEBUG - File "/tmp/pip-5nImSl-build/setup.py", line 82, in <module>
DEBUG - 'cloudify-plugins-common>=3.4'
DEBUG - File "/opt/cfy/embedded/lib/python2.7/distutils/core.py", line 151, in setup
DEBUG - dist.run_commands()
DEBUG - File "/opt/cfy/embedded/lib/python2.7/distutils/dist.py", line 953, in run_commands
DEBUG - self.run_command(cmd)
DEBUG - File "/opt/cfy/embedded/lib/python2.7/distutils/dist.py", line 972, in run_command
DEBUG - cmd_obj.run()
DEBUG - File "/opt/cfy/embedded/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 215, in run
DEBUG - self.run_command('install')
DEBUG - File "/opt/cfy/embedded/lib/python2.7/distutils/cmd.py", line 326, in run_command
DEBUG - self.distribution.run_command(command)
DEBUG - File "/opt/cfy/embedded/lib/python2.7/distutils/dist.py", line 972, in run_command
DEBUG - cmd_obj.run()
DEBUG - File "/tmp/pip-5nImSl-build/setup.py", line 68, in run
DEBUG - install_requirements()
DEBUG - File "/tmp/pip-5nImSl-build/setup.py", line 52, in install_requirements
DEBUG - pip_win_path = path.join(environ.get('VIRTUAL_ENV'), 'Scripts/pip.exe')
DEBUG - File "/opt/cfy/embedded/lib/python2.7/posixpath.py", line 77, in join
DEBUG - elif path == '' or path.endswith('/'):
DEBUG - AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by nir0s** [comment] 2016-09-12 09:56
Thanks. Will address that in the new version

**Comment by nir0s** [comment] 2017-01-05 11:36
Couldn't reproduce this. If this pops up again, will reopen.

**Comment by nir0s** [comment] 2017-01-12 06:52
I tried to use a python distribution installed in its own environment and didn't encounter any problems. Again, closing for now.

**Closed by nir0s** 2017-01-12 06:52 UTC
Labels: bug

**Comment by nir0s** [comment] 2017-11-28 09:35
Note that the potential fix for this, assuming the problem reappears, can be found here: https://github.com/cloudify-cosmo/wagon/tree/embedded_python_fix
